# Common configuration properties for all Ignition services
x-ignition-common: &ignition-common
  image: inductiveautomation/ignition:8.1.44
  depends_on:
    db:
      condition: service_healthy
  networks:
    - ignition_network
    - proxy
  volumes:
    - ./gw-init:/restore  # Mount the gw-init directory to /restore inside container

# Common environment variables for standard edition
x-standard-env: &standard-env
  IGNITION_EDITION: standard
  GATEWAY_MODULES_ENABLED: ${STD_MODULES:-perspective,tag-historian,web-developer,opc-ua,reporting,alarm-notification,sql-bridge,vision,voice-notification}
  TZ: ${TZ:-UTC}
  ACCEPT_IGNITION_EULA: "Y"

services:
  # Database service - shared across all configurations (PostgreSQL)
  db:
    image: postgres:latest
    container_name: ignition-db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-ignition}
      POSTGRES_USER: ${DB_USER:-ignition}
      POSTGRES_DB: ${DB_NAME:-ignition}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-ignition}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      ignition_network:
        aliases:
          - ignition-db
    profiles:
      - standard
      - scaleout
      - hubspoke
      - iiot

  # Standard standalone gateway configuration
  gateway:
    <<: *ignition-common
    container_name: ignition-gateway
    environment:
      <<: *standard-env
    labels:
      - traefik.enable=true
      - traefik.http.routers.ignition-gateway.rule=Host(`${GATEWAY_NAME:-ignition-gateway}.localtest.me`)
    command: >
      -n ${GATEWAY_NAME:-ignition-gateway}
      -h 80
      -s 443
      -a ${GATEWAY_NAME:-ignition-gateway}.localtest.me
      -r /restore/ignition-gateway.gwbk
      --
      -Dignition.projects.scanFrequency=10
    profiles:
      - standard

  # Frontend gateway for scale-out architecture
  frontend:
    <<: *ignition-common
    container_name: ignition-frontend
    environment:
      <<: *standard-env
      # Gateway Network configuration for backend
      GATEWAY_NETWORK_0_HOST: ignition-backend
      GATEWAY_NETWORK_0_PORT: 8088
      GATEWAY_NETWORK_0_ENABLESSL: "false"
      GATEWAY_NETWORK_0_DESCRIPTION: "Backend Connection"
      GATEWAY_NETWORK_ALLOWINCOMING: "false"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ignition-frontend.rule=Host(`${FRONTEND_NAME:-ignition-frontend}.localtest.me`)
    command: >
      -n ${FRONTEND_NAME:-ignition-frontend}
      -h 80
      -s 443
      -a ${FRONTEND_NAME:-ignition-frontend}.localtest.me
      -r /restore/ignition-frontend.gwbk
      --
      -Dignition.projects.scanFrequency=10
    profiles:
      - scaleout

  # Backend gateway for scale-out architecture
  backend:
    <<: *ignition-common
    container_name: ignition-backend
    environment:
      <<: *standard-env
      # Gateway Network Server configuration
      GATEWAY_NETWORK_REQUIRESSL: "false"
      GATEWAY_NETWORK_SECURITYPOLICY: "Unrestricted"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ignition-backend.rule=Host(`${BACKEND_NAME:-ignition-backend}.localtest.me`)
    command: >
      -n ${BACKEND_NAME:-ignition-backend}
      -h 80
      -s 443
      -a ${BACKEND_NAME:-ignition-backend}.localtest.me
      -r /restore/ignition-backend.gwbk
      --
      -Dignition.projects.scanFrequency=10
    profiles:
      - scaleout

  # Hub gateway for hub-and-spoke architecture
  hub:
    <<: *ignition-common
    container_name: ignition-hub
    environment:
      <<: *standard-env
      # Gateway Network Server configuration for spokes
      GATEWAY_NETWORK_REQUIRESSL: "false"
      GATEWAY_NETWORK_SECURITYPOLICY: "Unrestricted"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ignition-hub.rule=Host(`${HUB_NAME:-ignition-hub}.localtest.me`)
    command: >
      -n ${HUB_NAME:-ignition-hub}
      -h 80
      -s 443
      -a ${HUB_NAME:-ignition-hub}.localtest.me
      -r /restore/ignition-hub.gwbk
      --
      -Dignition.projects.scanFrequency=10
    profiles:
      - hubspoke

  # Spoke 1 gateway for hub-and-spoke architecture
  spoke1:
    <<: *ignition-common
    container_name: ignition-spoke1
    depends_on:
      hub:
        condition: service_healthy
    environment:
      <<: *standard-env
      # Gateway Network configuration for hub
      GATEWAY_NETWORK_0_HOST: ignition-hub
      GATEWAY_NETWORK_0_PORT: 8088
      GATEWAY_NETWORK_0_ENABLESSL: "false"
      GATEWAY_NETWORK_0_DESCRIPTION: "Hub Connection"
      GATEWAY_NETWORK_ALLOWINCOMING: "false"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ignition-spoke1.rule=Host(`${SPOKE1_NAME:-ignition-spoke1}.localtest.me`)
    command: >
      -n ${SPOKE1_NAME:-ignition-spoke1}
      -h 80
      -s 443
      -a ${SPOKE1_NAME:-ignition-spoke1}.localtest.me
      -r /restore/ignition-spoke1.gwbk
      --
      -Dignition.projects.scanFrequency=10
    profiles:
      - hubspoke

  # Spoke 2 gateway for hub-and-spoke architecture
  spoke2:
    <<: *ignition-common
    container_name: ignition-spoke2
    depends_on:
      hub:
        condition: service_healthy
    environment:
      <<: *standard-env
      # Gateway Network configuration for hub
      GATEWAY_NETWORK_0_HOST: ignition-hub
      GATEWAY_NETWORK_0_PORT: 8088
      GATEWAY_NETWORK_0_ENABLESSL: "false"
      GATEWAY_NETWORK_0_DESCRIPTION: "Hub Connection"
      GATEWAY_NETWORK_ALLOWINCOMING: "false"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ignition-spoke2.rule=Host(`${SPOKE2_NAME:-ignition-spoke2}.localtest.me`)
    command: >
      -n ${SPOKE2_NAME:-ignition-spoke2}
      -h 80
      -s 443
      -a ${SPOKE2_NAME:-ignition-spoke2}.localtest.me
      -r /restore/ignition-spoke2.gwbk
      --
      -Dignition.projects.scanFrequency=10
    profiles:
      - hubspoke
  
  # Spoke 3 gateway for hub-and-spoke architecture
  spoke3:
    <<: *ignition-common
    container_name: ignition-spoke3
    depends_on:
      hub:
        condition: service_healthy
    environment:
      <<: *standard-env
      # Gateway Network configuration for hub
      GATEWAY_NETWORK_0_HOST: ignition-hub
      GATEWAY_NETWORK_0_PORT: 8088
      GATEWAY_NETWORK_0_ENABLESSL: "false"
      GATEWAY_NETWORK_0_DESCRIPTION: "Hub Connection"
      GATEWAY_NETWORK_ALLOWINCOMING: "false"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ignition-spoke3.rule=Host(`${SPOKE3_NAME:-ignition-spoke3}.localtest.me`)
    command: >
      -n ${SPOKE3_NAME:-ignition-spoke3}
      -h 80
      -s 443
      -a ${SPOKE3_NAME:-ignition-spoke3}.localtest.me
      -r /restore/ignition-spoke3.gwbk
      --
      -Dignition.projects.scanFrequency=10
    profiles:
      - hubspoke

  # Ignition MQTT Central Gateway (with Engine + Distributor modules)
  mqtt-central:
    <<: *ignition-common
    container_name: ignition-mqtt-central
    environment:
      <<: *standard-env
    volumes:
      - ./gw-init:/restore
      - ./gw-modules/MQTT-Distributor-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Distributor-signed.modl
      - ./gw-modules/MQTT-Engine-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Engine-signed.modl
    labels:
      - traefik.enable=true
      - traefik.http.routers.ignition-mqtt-central.rule=Host(`${MQTT_CENTRAL_NAME:-ignition-mqtt-central}.localtest.me`)
    command: >
      -n ${MQTT_CENTRAL_NAME:-ignition-mqtt-central}
      -h 80
      -s 443
      -a ${MQTT_CENTRAL_NAME:-ignition-mqtt-central}.localtest.me
      -r /restore/ignition-mqtt-central.gwbk
      --
      -Dignition.projects.scanFrequency=10
    profiles:
      - iiot

  # Ignition MQTT Edge Gateways (with Transmission module)
  mqtt-edge1:
    <<: *ignition-common
    container_name: ignition-mqtt-edge1
    environment:
      <<: *standard-env
    volumes:
      - ./gw-init:/restore
      - ./gw-modules/MQTT-Transmission-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Transmission-signed.modl
    labels:
      - traefik.enable=true
      - traefik.http.routers.ignition-mqtt-edge1.rule=Host(`${MQTT_EDGE1_NAME:-ignition-mqtt-edge1}.localtest.me`)
    command: >
      -n ${MQTT_EDGE1_NAME:-ignition-mqtt-edge1}
      -h 80
      -s 443
      -a ${MQTT_EDGE1_NAME:-ignition-mqtt-edge1}.localtest.me
      -r /restore/ignition-mqtt-edge1.gwbk
      --
      -Dignition.projects.scanFrequency=10
    profiles:
      - iiot

  mqtt-edge2:
    <<: *ignition-common
    container_name: ignition-mqtt-edge2
    environment:
      <<: *standard-env
    volumes:
      - ./gw-init:/restore
      - ./gw-modules/MQTT-Transmission-signed.modl:/usr/local/bin/ignition/user-lib/modules/MQTT-Transmission-signed.modl
    labels:
      - traefik.enable=true
      - traefik.http.routers.ignition-mqtt-edge2.rule=Host(`${MQTT_EDGE2_NAME:-ignition-mqtt-edge2}.localtest.me`)
    command: >
      -n ${MQTT_EDGE2_NAME:-ignition-mqtt-edge2}
      -h 80
      -s 443
      -a ${MQTT_EDGE2_NAME:-ignition-mqtt-edge2}.localtest.me
      -r /restore/ignition-mqtt-edge2.gwbk
      --
      -Dignition.projects.scanFrequency=10
    profiles:
      - iiot

networks:
  ignition_network:
    driver: bridge
  proxy:
    external: true

volumes:
  db-data: